import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html className="dark:bg-black dark:text-white">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Chivo+Mono:wght@300&family=Roboto&display=swap"
          rel="stylesheet"
        ></link>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Chivo+Mono:wght@300&family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="m-0 p-0">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
